
export enum ActionTypes {
  SET_CURRENT_USER = "SET_CURRENT_USER",
  GET_ERRORS = "GET_ERRORS",
  FETCH_WORDS = "FETCH_WORDS",
  FETCH_SENTENCES = "FETCH_SENTENCES",
  FETCH_LESSONS = "FETCH_LESSONS",
  FETCH_QUESTIONS = "FETCH_QUESTIONS",
  FETCH_PROFILE = "FETCH_PROFILE",
  ADD_LEARNED_LESSON = "ADD_LEARNED_LESSON",
}

