export enum PracticeActionTypes {
  SET_CURRENT_SENTENCE = 'SET_CURRENT_SENTENCE',
  GET_CURRENT_SENTENCE = 'GET_CURRENT_SENTENCE',
  SET_CURRENT_LESSON = 'SET_CURRENT_LESSON',
  SET_CURRENT_TRANSLATION = 'SET_CURRENT_TRANSLATION',
}